### ISSUE TITLE
2.1.2 Signed Statement Registration MUST implement authentication.

### ISSUE THREAD

**Issue by roywill** [ietf-wg-scitt/draft-ietf-scitt-scrapi#19]
In the case of a government end point, why must client authentication be implemented.  The signature on the statement is the authentication for the content and is ultimately who is making a reputation statement.

**Comment by JAG-UK** [comment]
Agreed. In addition to this I think there are several places where we need to clean up seemingly helpful implementation comments which are actually harmful. For instance the mention of using auth for rate limiting is a fine thing to say but it's nothing to do with SCITT and will be done in other layers by any sensible implementation.

**Comment by SteveLasker** [comment]
Resolved by #28
