### ISSUE TITLE
using media types for errors

### ISSUE THREAD

**Issue by pdxjohnny** [ietf-wg-scitt/draft-ietf-scitt-scrapi#2]
Would be great to be able to return an object in addition to or instead of a string for errors. Or allow for other properties which would be fully content-typeable to a custom response object within the error response on claim insert failure.

Lack of this prevents an automated conversation to resolve issues with claim insertion. Human readable strings are great, but ideally a human doesn't even get involved and machines can auto remediate issues due to detailed failure reasoning. This way the a human readable string might only be needed after a failed machine driven insert conversation (more than one call response).

- References
  - https://github.com/ietf-scitt/draft-birkholz-scitt-scrapi/issues/4
    - https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/62

**Comment by aj-stein-nist** [comment]
I do agree but it seems per the spec we are following [RFC7807](https://www.rfc-editor.org/rfc/rfc7807#page-7) and they have this to say about our desired change in this request.

   Consumers SHOULD NOT parse the "detail" member for information;
   extensions are more suitable and less error-prone ways to obtain such
   information.

I am looking more into these mysterious "extensions" mentioned in this spec.

**Comment by SteveLasker** [comment]
Editors call discussion: All errors should be returned with json object.
Reference the review: https://datatracker.ietf.org/doc/review-ietf-scitt-scrapi-01-httpdir-early-miller-2024-03-10/
Ready for PR

**Comment by henkbirkholz** [comment]
PR incoming for application/problem+json response from @aj-stein-nist

**Comment by aj-stein-nist** [comment]
I am going to work on the PR. I didn't realize the content type is properly set per the commits above in [`e2f23a9`](https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/blob/e2f23a9ce8621f3a4392608c2f97c85c2a32fcdf/draft-ietf-scitt-scrapi.md?plain=1#L118). So I will PR the follow on extension bit for custom fields in the PR. If there is no consensus, we can stick with `"detail": "..."` with the appropriate content type and close it out when rejecting the PR.

**Comment by aj-stein-nist** [comment]
Per discussion on the editor's call, no one can see an immediate need for use of extension fields per the cited RFC for specific, structured data for error message for debugging or reporting.

I am closing for now. We can revisit later as the need comes up. The content types for errors are already used today.

**Comment by aj-stein-nist** [comment]
@SteveLasker or other authors that own this repo, I cannot close this issue because I did not create this issues, apologies. I need one of you to close the issue for me.

**Comment by roywill** [comment]
I like the guidance we are giving in this area, but we use an example to define the specific error to return.  

    As an example, submitting a Signed Statement with an unsupported signature algorithm **would** return a 400 Bad Request status code and the following body:

Must it be 400 or is that a suggestion?

**Comment by JAG-UK** [comment]
> Must it be 400 or is that a suggestion?

has to be a MAY or "might" or "could" or something. Surely.

**Comment by SteveLasker** [comment]
closing, with #25 as the next step
