### ISSUE TITLE
Add support for multiple notaries

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-scrapi#33]
On the register statement API, a TS could be a front end to multiple Transparency Services. It may be hashed by country or industry. 
The question is whether the API should add a parameter for which Notary to use, or it may be inferred by other parameters, or the identity of the client.

**Comment by aj-stein** [comment]
> On the register statement API, a TS could be a front end to multiple Transparency Services. It may be hashed by country or industry. The question is whether the API should add a parameter for which Notary to use, or it may be inferred by other parameters, or the identity of the client.

Since no one else has commented, I will chime in: I think that is a concern for client software to handle without adding API surface to part of the reference API for TS implementations. I would prefer to not have this addition.

**Comment by achamayou** [comment]
+1 for keeping the API simple, and not adding this. Deployments that need this functionality should be able to deploy a separate service out in front that redirects/load balances as desired.

It seems likely that the regional instances would be different issuers (perhaps subdomains), and so trying to present a unified endpoint also means working out how to present a unified transparency configuration also, adding complexity there too.

**Comment by JAG-UK** [comment]
The way the reference implementation is shaping up in scitt-community it would be easy for the client to establish multiple connections and send multiple copies if it knows that it needs to. This is nice and clean and I support the comments here to not muddy the API with such things.

I've heard talk of use casses where the client might not know it needs to do tat, or that there is benefit in having one single request result in multiple receipts, but I don't think the advantages are clear enough to try to build an API for right now. Even in these cases nothing stops the TS from registering in multiple places.

**Comment by achamayou** [comment]
I think that's resolved to some extent by the client using a statement API, because the first service can turn around and submit to one or more other TS, who will append their receipts to the statement. The first TS can then return the statement to the client who needs no special handling.

Something like:

```mermaid
sequenceDiagram
    Client->>+TS0: Signed Statement
    TS0->>TS0: Add Receipt[0] to Signed Statement<br>.a.k.a Transparent Statement
    TS0->>+TS1: Register Transparent Statement with Receipt[0]
    TS1->>-TS0: Transparent Statement with Receipt[0, 1]
    TS0->>-Client: Transparent Statement with Receipt[0, 1]
```

Or:

```mermaid
sequenceDiagram
    Client->>+TS0: Signed Statement
    TS0->>TS0: Add Receipt[0] to Signed Statement<br>.a.k.a Transparent Statement
    TS0->>+TS1: Register Transparent Statement with Receipt[0]
    TS1->>-TS0: Fetch Receipt[1]
    TS0->>TS0: Add Receipt[0, 1] to Signed Statement
    TS0->>-Client: Transparent Statement with Receipt[0, 1]
```

This may be a registration policy that TS0 applies to statements that meet certain criteria. "if conditions are met, get receipts from the other two regions before returning a statement with all three receipts to the caller".

**Comment by SteveLasker** [comment]
Closing based on prior editors call discussions.
It was originally requested by @roywill. Please re-activate if you feel we still need this.
