### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by aj-stein-nist** [ietf-wg-scitt/draft-ietf-scitt-scrapi#4]
I am not sure this is within the scope of the formal working group or better as an "outside" community effort, but with the relocation of this draft into the ietf-wg-scitt org and its upload to datatracker, have we considered having a test suite with sample artifacts, signed statements, and transparent statements that conform to the API spec here as a test harness of sorts? I have seen *some* IETF and other standard bodies groups making such test suites. I am opening this issue here to gauge interest and determine if making it "inline in this repo" is within scope or not.

**Comment by SteveLasker** [comment]
Good to have a test suite, but we haven't been maintaining the emulator. 
Keeping for further discussion.

**Comment by aj-stein-nist** [comment]
Per discussion on an editors' call today, there was a good discussion around the scope of work around the reference implementation based on the SCRAPI specification. That would require layering on top of the specification, picking optional implementation choices for authentication, identities, and other decisions outside the scope of the architecture as well. Also picking statements about artifact and dealing with the opaqueness of it in a way is further beyond the scope of the IETF WG.

Others on the call would welcome such an effort as a community work item, but not to be maintained in this repo or GitHub organization. I will volunteer to pursue this work in the [SCITT Community](https://github.com/scitt-community/). I am closing this issue for now.
