### ISSUE TITLE
Remove 'ResolveStatement' and associated IDs/references

### ISSUE THREAD

**Issue by JAG-UK** [ietf-wg-scitt/draft-ietf-scitt-scrapi#44]
It's sufficient/better to just ResolveSignedStatement (meaning you get back what was put in) and then the client can pull the Statement out if they want it. Reduces complexity for no loss of functionality

**Comment by aj-stein** [comment]
> It's sufficient/better to just ResolveSignedStatement (meaning you get back what was put in) and then the client can pull the Statement out if they want it. Reduces complexity for no loss of functionality

So no separate endpoint, you mean?

**Comment by JAG-UK** [comment]
Reviewed and merged in #38
