### ISSUE TITLE
Minimally viable `/.well-known/transparency-configuration` CDDL for TS configruation?

### ISSUE THREAD

**Issue by aj-stein** [ietf-wg-scitt/draft-ietf-scitt-scrapi#45]
Since we are talking about #36, does this mean we must refactor this API endpoint's response with minimally viable CBOR and a CDDL spec in place of JSON?

**Comment by JAG-UK** [comment]
Yes. Discussed at the hackathon and will make a proposal as part of https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/pull/38

**Comment by JAG-UK** [comment]
Added to PR #38 - LMK if you like it

**Comment by aj-stein** [comment]
I will have to experiment with it more, but so far I like it. You can link this issue to close it once you merge #39. Thanks.
